"""
mcp_server.py — Energy Management MCP Server
=============================================
Uses the official MCP library (FastMCP) to register all tools with proper
MCP-compliant schemas and handlers.

The MCPServer class wraps FastMCP and exposes:
  - call_tool(tool_name, parameters)  → used by app.py for direct dispatch
  - turn_on_device / turn_off_device / set_motor_intensity → used by app.py
    during plan approval execution
  - fmcp  → the FastMCP instance (can be used to run the MCP server standalone)

All 9 tools are registered with FastMCP so they are discoverable by any
MCP-compatible client (Claude Desktop, Cursor, etc.) while remaining fully
callable by app.py through the MCPServer wrapper.

All timestamps generated by this server use Kuwait time (Asia/Kuwait, UTC+3).
"""

import json
import pytz
from datetime import datetime, timedelta
from database import db
import config
import paho.mqtt.client as mqtt

from mcp.server.fastmcp import FastMCP
from mcp.types import Tool, TextContent

# ── Timezone ──────────────────────────────────────────────────────────────────
KUWAIT_TZ = pytz.timezone('Asia/Kuwait')

def _now_kuwait() -> str:
    """Return the current datetime in Kuwait time as an ISO8601 string."""
    return datetime.now(KUWAIT_TZ).isoformat()

# ── MQTT configuration for Athom plug (Light Bulb) ───────────────────────────

MQTT_BROKER_IP    = config.MQTT_BROKER_IP
MQTT_BROKER_PORT  = config.MQTT_BROKER_PORT
MQTT_DEVICE_TOPIC = config.MQTT_DEVICE_TOPIC
MQTT_COMMAND_TOPIC = f"cmnd/{MQTT_DEVICE_TOPIC}/POWER"

mqtt_client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1, protocol=mqtt.MQTTv311)


def publish_light_command(command: str) -> bool:
    """Publish ON/OFF command to Athom plug via MQTT."""
    try:
        mqtt_client.connect(MQTT_BROKER_IP, MQTT_BROKER_PORT, 60)
        mqtt_client.publish(MQTT_COMMAND_TOPIC, command)
        mqtt_client.disconnect()
        print(f"✓ Sent {command} command to Light Bulb via MQTT")
        return True
    except Exception as e:
        print(f"✗ Failed to send MQTT command: {e}")
        return False


# ── FastMCP instance ──────────────────────────────────────────────────────────

fmcp = FastMCP("energy-management-mcp-server")


# ── Tool registrations (FastMCP @fmcp.tool decorators) ───────────────────────
# Each function is registered as a proper MCP tool with a typed signature.
# FastMCP automatically derives the JSON schema from the type hints.
# The MCPServer class below wraps these same functions for use by app.py.

@fmcp.tool(
    name="turn_on",
    description="Turn on a device. Supported devices: Motor, Fan, Light Bulb."
)
def _tool_turn_on(device: str) -> dict:
    """
    Turn on a device.

    Args:
        device: Name of the device to turn on. One of: 'Motor', 'Fan', 'Light Bulb'.
    """
    if device == "Motor":
        db.update_device_status(config.MOTOR_ID, "ON")
        return {"success": True, "message": "Motor turned ON"}
    elif device == "Fan":
        db.update_device_status(config.FAN_ID, "ON")
        return {"success": True, "message": "Fan turned ON"}
    elif device == "Light Bulb":
        if publish_light_command("ON"):
            db.update_device_status(config.LIGHT_BULB_ID, "ON")
            return {"success": True, "message": "Light Bulb turned ON"}
        else:
            return {"error": "Failed to turn on Light Bulb via MQTT"}
    else:
        return {"error": f"Unknown device: {device}"}


@fmcp.tool(
    name="turn_off",
    description="Turn off a device. Supported devices: Motor, Fan, Light Bulb."
)
def _tool_turn_off(device: str) -> dict:
    """
    Turn off a device.

    Args:
        device: Name of the device to turn off. One of: 'Motor', 'Fan', 'Light Bulb'.
    """
    if device == "Motor":
        db.update_device_status(config.MOTOR_ID, "OFF")
        return {"success": True, "message": "Motor turned OFF"}
    elif device == "Fan":
        db.update_device_status(config.FAN_ID, "OFF")
        return {"success": True, "message": "Fan turned OFF"}
    elif device == "Light Bulb":
        if publish_light_command("OFF"):
            db.update_device_status(config.LIGHT_BULB_ID, "OFF")
            return {"success": True, "message": "Light Bulb turned OFF"}
        else:
            return {"error": "Failed to turn off Light Bulb via MQTT"}
    else:
        return {"error": f"Unknown device: {device}"}


@fmcp.tool(
    name="set_motor_intensity",
    description="Set the DC motor intensity as a percentage (0–100). "
                "100% corresponds to approximately 350 W."
)
def _tool_set_motor_intensity(percent_0_to_100: float) -> dict:
    """
    Set motor intensity.

    Args:
        percent_0_to_100: Motor intensity percentage between 0 and 100.
    """
    if percent_0_to_100 is None or not (0 <= percent_0_to_100 <= 100):
        return {"error": "Invalid intensity value. Must be between 0 and 100"}
    db.update_device_intensity(config.MOTOR_ID, str(percent_0_to_100))
    power = (percent_0_to_100 / 100.0) * 350
    return {
        "success": True,
        "message": f"Motor intensity set to {percent_0_to_100}%",
        "power_w": power
    }


@fmcp.tool(
    name="db_read",
    description=(
        "Query the energy management database. "
        "query_type options: "
        "'latest_device_status' — returns all devices and their current status; "
        "'current_total_consumption' — returns total energy consumed in Wh and kWh; "
        "'device_consumption' — returns consumption for a specific device (requires device_id); "
        "'budget' — returns the configured energy budget in kWh and Wh; "
        "'historical_consumption' — returns time-series readings for a device (requires device_id, optional hours)."
    )
)
def _tool_db_read(
    query_type: str,
    device_id: int = None,
    hours: int = 24
) -> dict:
    """
    Query the database.

    Args:
        query_type: Type of query. One of: latest_device_status, current_total_consumption,
                    device_consumption, budget, historical_consumption.
        device_id:  Device ID (required for device_consumption and historical_consumption).
        hours:      Number of hours of history to retrieve (default 24).
    """
    if query_type == "latest_device_status":
        devices = db.get_all_devices()
        return {"devices": [dict(d) for d in devices]}

    elif query_type == "current_total_consumption":
        system_config = db.get_system_config()
        return {
            "total_consumption_wh":  system_config['total_consumption'],
            "total_consumption_kwh": system_config['total_consumption'] / 1000
        }

    elif query_type == "device_consumption":
        device = db.get_device(device_id)
        if device:
            return {
                "device_id":       device['id'],
                "device_name":     device['device_name'],
                "consumption_wh":  device['device_total_consumption'],
                "consumption_kwh": device['device_total_consumption'] / 1000
            }
        return {"error": "Device not found"}

    elif query_type == "budget":
        system_config = db.get_system_config()
        return {
            "energy_budget_kwh": system_config['energy_budget'],
            "energy_budget_wh":  system_config['energy_budget'] * 1000
        }

    elif query_type == "historical_consumption":
        readings = db.get_recent_readings(device_id, hours)
        return {"readings": [dict(r) for r in readings]}

    else:
        return {"error": f"Unknown query type: {query_type}"}


@fmcp.tool(
    name="read_system_status",
    description="Get the complete system status: all device states, total consumption, "
                "energy budget, and whether the budget has been exceeded."
)
def _tool_read_system_status() -> dict:
    """Get complete system status."""
    system_config = db.get_system_config()
    devices = db.get_all_devices()

    total_consumption = system_config['total_consumption']
    energy_budget     = system_config['energy_budget'] * 1000  # convert kWh → Wh

    status = "Normal" if total_consumption <= energy_budget else "Exceeded"

    return {
        "system_status":        status,
        "total_consumption_wh": total_consumption,
        "energy_budget_wh":     energy_budget,
        "devices":              [dict(d) for d in devices],
        "last_update":          _now_kuwait()   # Kuwait time
    }


@fmcp.tool(
    name="request_human_approval",
    description="Submit an optimization plan for human review and approval. "
                "The plan will be held in a pending state until the operator approves or rejects it."
)
def _tool_request_human_approval(plan: str) -> dict:
    """
    Request human approval for an optimization plan.

    Args:
        plan: A string description of the optimization plan to be approved.
    """
    return {
        "approval_status": "pending",
        "message":         "Plan submitted for human approval",
        "plan":            plan
    }


@fmcp.tool(
    name="generate_optimization_schedules",
    description="Generate a set of pre-defined energy optimization schedule templates "
                "based on how much the budget has been exceeded."
)
def _tool_generate_optimization_schedules(budget_exceeded_by_wh: float = 0) -> dict:
    """
    Generate optimization schedule templates.

    Args:
        budget_exceeded_by_wh: The amount by which the energy budget has been exceeded, in Wh.
    """
    schedules = [
        {
            "name": "Reduce Motor to 50%",
            "actions": [{"device": "Motor", "action": "set_intensity", "value": 50}],
            "estimated_savings_wh": 175 * 3600,
        },
        {
            "name": "Turn Off Fan",
            "actions": [{"device": "Fan", "action": "turn_off"}],
            "estimated_savings_wh": 80 * 3600,
        },
        {
            "name": "Turn Off Light Bulb",
            "actions": [{"device": "Light Bulb", "action": "turn_off"}],
            "estimated_savings_wh": 60 * 3600,
        },
        {
            "name": "Reduce Motor to 30% and Turn Off Fan",
            "actions": [
                {"device": "Motor", "action": "set_intensity", "value": 30},
                {"device": "Fan",   "action": "turn_off"}
            ],
            "estimated_savings_wh": (245 + 80) * 3600,
        },
        {
            "name": "Turn Off All Non-Essential Devices",
            "actions": [
                {"device": "Fan",        "action": "turn_off"},
                {"device": "Light Bulb", "action": "turn_off"}
            ],
            "estimated_savings_wh": 140 * 3600,
        },
    ]
    return {"schedules": schedules}


@fmcp.tool(
    name="generate_energy_report",
    description="Generate an energy consumption report for a given time period. "
                "period: 'today', 'week', or 'month'. "
                "report_type: 'summary' or 'detailed'."
)
def _tool_generate_energy_report(
    period: str = "today",
    report_type: str = "summary"
) -> dict:
    """
    Generate an energy report.

    Args:
        period:      Reporting period. One of: 'today', 'week', 'month'.
        report_type: Report detail level. One of: 'summary', 'detailed'.
    """
    devices = db.get_all_devices()
    system_config = db.get_system_config()

    report = {
        "period":               period,
        "report_type":          report_type,
        "generated_at":         _now_kuwait(),   # Kuwait time
        "total_consumption_kwh": system_config['total_consumption'] / 1000,
        "energy_budget_kwh":    system_config['energy_budget'],
        "devices":              []
    }

    for device in devices:
        report["devices"].append({
            "name":            device['device_name'],
            "status":          device['device_status'],
            "consumption_kwh": device['device_total_consumption'] / 1000,
            "percentage":      (
                device['device_total_consumption'] / system_config['total_consumption'] * 100
                if system_config['total_consumption'] > 0 else 0
            )
        })

    return report


@fmcp.tool(
    name="calculate_energy_metrics",
    description="Calculate derived energy metrics from raw electrical measurements."
)
def _tool_calculate_energy_metrics(
    power_w:        float = 0,
    voltage_v:      float = 220,
    current_a:      float = 0,
    runtime_hours:  float = 1
) -> dict:
    """
    Calculate energy metrics.

    Args:
        power_w:       Active power in Watts.
        voltage_v:     Voltage in Volts (default 220 V).
        current_a:     Current in Amperes.
        runtime_hours: Operating duration in hours (default 1 h).
    """
    energy_kwh         = (power_w * runtime_hours) / 1000
    apparent_power_va  = voltage_v * current_a
    power_factor       = power_w / apparent_power_va if apparent_power_va > 0 else 0
    reactive_power_var = (
        (apparent_power_va ** 2 - power_w ** 2) ** 0.5
        if apparent_power_va > power_w else 0
    )
    co2_emissions_kg   = energy_kwh * 0.5

    return {
        "energy_kwh":          energy_kwh,
        "apparent_power_va":   apparent_power_va,
        "power_factor":        power_factor,
        "reactive_power_var":  reactive_power_var,
        "co2_emissions_kg":    co2_emissions_kg,
    }


# ── MCPServer wrapper (used by app.py) ────────────────────────────────────────

class MCPServer:
    """
    Thin wrapper around the FastMCP tool functions.
    Provides the same interface that app.py expects:
      - call_tool(tool_name, parameters)
      - turn_on_device(params)
      - turn_off_device(params)
      - set_motor_intensity(params)
    """

    def __init__(self):
        self.tools = {
            "turn_on":                       self.turn_on_device,
            "turn_off":                      self.turn_off_device,
            "set_motor_intensity":           self.set_motor_intensity,
            "db_read":                       self.db_read,
            "read_system_status":            self.read_system_status,
            "request_human_approval":        self.request_human_approval,
            "generate_optimization_schedules": self.generate_optimization_schedules,
            "generate_energy_report":        self.generate_energy_report,
            "calculate_energy_metrics":      self.calculate_energy_metrics,
        }
        print("✓ MCP Server initialized with 9 registered tools")

    def call_tool(self, tool_name: str, parameters: dict) -> dict:
        if tool_name in self.tools:
            return self.tools[tool_name](parameters)
        return {"error": f"Unknown tool: {tool_name}"}

    # ── Device control ────────────────────────────────────────────────────────

    def turn_on_device(self, params: dict) -> dict:
        return _tool_turn_on(params.get("device"))

    def turn_off_device(self, params: dict) -> dict:
        return _tool_turn_off(params.get("device"))

    def set_motor_intensity(self, params: dict) -> dict:
        return _tool_set_motor_intensity(params.get("percent_0_to_100"))

    # ── Data / query tools ────────────────────────────────────────────────────

    def db_read(self, params: dict) -> dict:
        return _tool_db_read(
            query_type=params.get("query_type"),
            device_id=params.get("device_id"),
            hours=params.get("hours", 24)
        )

    def read_system_status(self, params: dict) -> dict:
        return _tool_read_system_status()

    def request_human_approval(self, params: dict) -> dict:
        return _tool_request_human_approval(params.get("plan", ""))

    def generate_optimization_schedules(self, params: dict) -> dict:
        return _tool_generate_optimization_schedules(
            params.get("budget_exceeded_by_wh", 0)
        )

    def generate_energy_report(self, params: dict) -> dict:
        return _tool_generate_energy_report(
            period=params.get("period", "today"),
            report_type=params.get("report_type", "summary")
        )

    def calculate_energy_metrics(self, params: dict) -> dict:
        return _tool_calculate_energy_metrics(
            power_w=params.get("power_w", 0),
            voltage_v=params.get("voltage_v", 220),
            current_a=params.get("current_a", 0),
            runtime_hours=params.get("runtime_hours", 1)
        )


mcp_server = MCPServer()
